language: node_js
node_js:
  - "0.11"
  - "0.10"
script:
- ./node_modules/.bin/mocha --reporter spec
- ./node_modules/.bin/mocha --require blanket --reporter mocha-lcov-reporter | > coverage.out
after_script:
- ./node_modules/.bin/coveralls < coverage.out
