language: node_js
node_js:
  - "0.11"
  - "0.10"
  - "0.8"
  - "0.6"
script:
  - ./node_modules/.bin/mocha --require blanket --reporter mocha-lcov-reporter > coverage.out
aftaer_script:
  - ./node_modules/.bin/coveralls < coverage.out
